// server.js
// const express = require('express');
// const path = require('path');

// const app = express();

// // Serve static files generated by Vite
// app.use(express.static(path.join(__dirname, 'dist')));

// // Handle all routes and return the main index.html file
// app.get('*', (req, res) => {
//   res.sendFile(path.join(__dirname, 'dist', 'index.html'));
// });

// // Start the server
// const port = process.env.PORT || 3000;
// app.listen(port, () => {
//   console.log(`Server started on port ${port}`);
// });
